name: Build & Deploy API

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: |
         cd EspApi
          dotnet restore

      - name: Build
        run: |
          cd EspApi
          dotnet build --configuration Release --no-restore

      - name: Publish
        run: |
          cd EspApi
          dotnet publish -c Release -o ../out

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: espapi
          path: out/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: espapi

      - name: Copy to VPS & Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: 10378               # 🔥 ważne: Twój port SSH
          key: ${{ secrets.VPS_KEY }}
          source: "./EspApi/"
          target: "/home/${{ secrets.VPS_USER }}/espapi"

      - name: Restart Docker container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: 10378               # 🔥 również tutaj
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd "./EspApi/"
            cd /home/${{ secrets.VPS_USER }}/espapi
            docker build -t espapi .
            docker stop espapi || true
            docker rm espapi || true
            docker run -d -p 8080:8080 --name espapi espapi
